#Take home Project

In [1]:
import numpy as np
import pandas as pd
from google.colab import drive

drive.mount("/content/drive")

pd.set_option("display.max_columns", 80)
pd.set_option("display.max_colwidth", 120)

columns_path = "/content/drive/MyDrive/Colab Notebooks/census-bureau.columns"
data_path = "/content/drive/MyDrive/Colab Notebooks/census-bureau.data"

Mounted at /content/drive

In [2]:
with open(columns_path, "r") as f:
    column_names = [line.strip() for line in f if line.strip()]

df = pd.read_csv(data_path, header=None, names=column_names)

print(f"Columns loaded: {len(column_names)}")
print(f"Dataset shape: {df.shape[0]:,} rows x {df.shape[1]:,} columns")

pd.DataFrame({"column_number": range(1, len(column_names) + 1), "column_name": column_names})

Columns loaded: 42
Dataset shape: 199,523 rows x 42 columns

    column_number                                 column_name
0               1                                         age
1               2                             class of worker
2               3                    detailed industry recode
3               4                  detailed occupation recode
4               5                                   education
5               6                               wage per hour
6               7                  enroll in edu inst last wk
7               8                                marital stat
8               9                         major industry code
9              10                       major occupation code
10             11                                        race
11             12                             hispanic origin
12             13                                         sex
13             14                     member of a labor union
14             15                     reason for unemployment
15             16           full or part time employment stat
16             17                               capital gains
17             18                              capital losses
18             19                       dividends from stocks
19             20                              tax filer stat
20             21                region of previous residence
21             22                 state of previous residence
22             23          detailed household and family stat
23             24     detailed household summary in household
24             25                                      weight
25             26                migration code-change in msa
26             27                migration code-change in reg
27             28              migration code-move within reg
28             29               live in this house 1 year ago
29             30               migration prev res in sunbelt
30             31             num persons worked for employer
31             32                     family members under 18
32             33                     country of birth father
33             34                     country of birth mother
34             35                       country of birth self
35             36                                 citizenship
36             37               own business or self employed
37             38  fill inc questionnaire for veteran's admin
38             39                           veterans benefits
39             40                        weeks worked in year
40             41                                        year
41             42                                       label

In [3]:
df.head()

,age,class of worker,detailed industry recode,detailed occupation recode,education,wage per hour,enroll in edu inst last wk,marital stat,major industry code,major occupation code,race,hispanic origin,sex,member of a labor union,reason for unemployment,full or part time employment stat,capital gains,capital losses,dividends from stocks,tax filer stat,region of previous residence,state of previous residence,detailed household and family stat,detailed household summary in household,weight,migration code-change in msa,migration code-change in reg,migration code-move within reg,live in this house 1 year ago,migration prev res in sunbelt,num persons worked for employer,family members under 18,country of birth father,country of birth mother,country of birth self,citizenship,own business or self employed,fill inc questionnaire for veteran's admin,veterans benefits,weeks worked in year,year,label
0,73,Not in universe,0,0,High school graduate,0,Not in universe,Widowed,Not in universe or children,Not in universe,White,All other,Female,Not in universe,Not in universe,Not in labor force,0,0,0,Nonfiler,Not in universe,Not in universe,Other Rel 18+ ever marr not in subfamily,Other relative of householder,1700.09,?,?,?,Not in universe under 1 year old,?,0,Not in universe,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,95,- 50000.
1,58,Self-employed-not incorporated,4,34,Some college but no degree,0,Not in universe,Divorced,Construction,Precision production craft & repair,White,All other,Male,Not in universe,Not in universe,Children or Armed Forces,0,0,0,Head of household,South,Arkansas,Householder,Householder,1053.55,MSA to MSA,Same county,Same county,No,Yes,1,Not in universe,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,- 50000.
2,18,Not in universe,0,0,10th grade,0,High school,Never married,Not in universe or children,Not in universe,Asian or Pacific Islander,All other,Female,Not in universe,Not in universe,Not in labor force,0,0,0,Nonfiler,Not in universe,Not in universe,Child 18+ never marr Not in a subfamily,Child 18 or older,991.95,?,?,?,Not in universe under 1 year old,?,0,Not in universe,Vietnam,Vietnam,Vietnam,Foreign born- Not a citizen of U S,0,Not in universe,2,0,95,- 50000.
3,9,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,White,All other,Female,Not in universe,Not in universe,Children or Armed Forces,0,0,0,Nonfiler,Not in universe,Not in universe,Child <18 never marr not in subfamily,Child under 18 never married,1758.14,Nonmover,Nonmover,Nonmover,Yes,Not in universe,0,Both parents present,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,- 50000.
4,10,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,White,All other,Female,Not in universe,Not in universe,Children or Armed Forces,0,0,0,Nonfiler,Not in universe,Not in universe,Child <18 never marr not in subfamily,Child under 18 never married,1069.16,Nonmover,Nonmover,Nonmover,Yes,Not in universe,0,Both parents present,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,- 50000.

In [4]:
basic_check = pd.DataFrame({
    "dtype": df.dtypes.astype(str),
    "non_null_count": df.notna().sum(),
    "null_count": df.isna().sum(),
    "unique_values": df.nunique(dropna=True),
})

basic_check

,dtype,non_null_count,null_count,unique_values
age,int64,199523,0,91
class of worker,object,199523,0,9
detailed industry recode,int64,199523,0,52
detailed occupation recode,int64,199523,0,47
education,object,199523,0,17
wage per hour,int64,199523,0,1240
enroll in edu inst last wk,object,199523,0,3
marital stat,object,199523,0,7
major industry code,object,199523,0,24
major occupation code,object,199523,0,15
race,object,199523,0,5
hispanic origin,object,198649,874,9
sex,object,199523,0,2
member of a labor union,object,199523,0,3
reason for unemployment,object,199523,0,6
full or part time employment stat,object,199523,0,8
capital gains,int64,199523,0,132
capital losses,int64,199523,0,113
dividends from stocks,int64,199523,0,1478
tax filer stat,object,199523,0,6
region of previous residence,object,199523,0,6
state of previous residence,object,199523,0,51
detailed household and family stat,object,199523,0,38
detailed household summary in household,object,199523,0,8
weight,float64,199523,0,99800
migration code-change in msa,object,199523,0,10
migration code-change in reg,object,199523,0,9
migration code-move within reg,object,199523,0,10
live in this house 1 year ago,object,199523,0,3
migration prev res in sunbelt,object,199523,0,4
num persons worked for employer,int64,199523,0,7
family members under 18,object,199523,0,5
country of birth father,object,199523,0,43
country of birth mother,object,199523,0,43
country of birth self,object,199523,0,43
citizenship,object,199523,0,5
own business or self employed,int64,199523,0,3
fill inc questionnaire for veteran's admin,object,199523,0,3
veterans benefits,int64,199523,0,3
weeks worked in year,int64,199523,0,53
year,int64,199523,0,2
label,object,199523,0,2

In [5]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
age,199523.0,NaN,NaN,NaN,34.494199,22.310895,0.0,15.0,33.0,50.0,90.0
class of worker,199523,9,Not in universe,100245,NaN,NaN,NaN,NaN,NaN,NaN,NaN
detailed industry recode,199523.0,NaN,NaN,NaN,15.35232,18.067129,0.0,0.0,0.0,33.0,51.0
detailed occupation recode,199523.0,NaN,NaN,NaN,11.306556,14.454204,0.0,0.0,0.0,26.0,46.0
education,199523,17,High school graduate,48407,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wage per hour,199523.0,NaN,NaN,NaN,55.426908,274.896454,0.0,0.0,0.0,0.0,9999.0
enroll in edu inst last wk,199523,3,Not in universe,186943,NaN,NaN,NaN,NaN,NaN,NaN,NaN
marital stat,199523,7,Never married,86485,NaN,NaN,NaN,NaN,NaN,NaN,NaN
major industry code,199523,24,Not in universe or children,100684,NaN,NaN,NaN,NaN,NaN,NaN,NaN
major occupation code,199523,15,Not in universe,100684,NaN,NaN,NaN,NaN,NaN,NaN,NaN
race,199523,5,White,167365,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hispanic origin,198649,9,All other,171907,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sex,199523,2,Female,103984,NaN,NaN,NaN,NaN,NaN,NaN,NaN
member of a labor union,199523,3,Not in universe,180459,NaN,NaN,NaN,NaN,NaN,NaN,NaN
reason for unemployment,199523,6,Not in universe,193453,NaN,NaN,NaN,NaN,NaN,NaN,NaN
full or part time employment stat,199523,8,Children or Armed Forces,123769,NaN,NaN,NaN,NaN,NaN,NaN,NaN
capital gains,199523.0,NaN,NaN,NaN,434.71899,4697.53128,0.0,0.0,0.0,0.0,99999.0
capital losses,199523.0,NaN,NaN,NaN,37.313788,271.896428,0.0,0.0,0.0,0.0,4608.0
dividends from stocks,199523.0,NaN,NaN,NaN,197.529533,1984.163658,0.0,0.0,0.0,0.0,99999.0
tax filer stat,199523,6,Nonfiler,75094,NaN,NaN,NaN,NaN,NaN,NaN,NaN
region of previous residence,199523,6,Not in universe,183750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
state of previous residence,199523,51,Not in universe,183750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
detailed household and family stat,199523,38,Householder,53248,NaN,NaN,NaN,NaN,NaN,NaN,NaN
detailed household summary in household,199523,8,Householder,75475,NaN,NaN,NaN,NaN,NaN,NaN,NaN
weight,199523.0,NaN,NaN,NaN,1740.380269,993.768156,37.87,1061.615,1618.31,2188.61,18656.3
migration code-change in msa,199523,10,?,99696,NaN,NaN,NaN,NaN,NaN,NaN,NaN
migration code-change in reg,199523,9,?,99696,NaN,NaN,NaN,NaN,NaN,NaN,NaN
migration code-move within reg,199523,10,?,99696,NaN,NaN,NaN,NaN,NaN,NaN,NaN
live in this house 1 year ago,199523,3,Not in universe under 1 year old,101212,NaN,NaN,NaN,NaN,NaN,NaN,NaN
migration prev res in sunbelt,199523,4,?,99696,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num persons worked for employer,199523.0,NaN,NaN,NaN,1.95618,2.365126,0.0,0.0,1.0,4.0,6.0
family members under 18,199523,5,Not in universe,144232,NaN,NaN,NaN,NaN,NaN,NaN,NaN
country of birth father,199523,43,United-States,159163,NaN,NaN,NaN,NaN,NaN,NaN,NaN
country of birth mother,199523,43,United-States,160479,NaN,NaN,NaN,NaN,NaN,NaN,NaN
country of birth self,199523,43,United-States,176989,NaN,NaN,NaN,NaN,NaN,NaN,NaN
citizenship,199523,5,Native- Born in the United States,176992,NaN,NaN,NaN,NaN,NaN,NaN,NaN
own business or self employed,199523.0,NaN,NaN,NaN,0.175438,0.553694,0.0,0.0,0.0,0.0,2.0
fill inc questionnaire for veteran's admin,199523,3,Not in universe,197539,NaN,NaN,NaN,NaN,NaN,NaN,NaN
veterans benefits,199523.0,NaN,NaN,NaN,1.514833,0.851473,0.0,2.0,2.0,2.0,2.0
weeks worked in year,199523.0,NaN,NaN,NaN,23.174897,24.411488,0.0,0.0,8.0,52.0,52.0
year,199523.0,NaN,NaN,NaN,94.499672,0.500001,94.0,94.0,94.0,95.0,95.0
label,199523,2,- 50000.,187141,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df_clean = df.copy()

text_cols = df_clean.select_dtypes(include="object").columns
for col in text_cols:
    df_clean[col] = df_clean[col].str.strip()

df_clean = df_clean.replace("?", pd.NA)

df_clean.head()

,age,class of worker,detailed industry recode,detailed occupation recode,education,wage per hour,enroll in edu inst last wk,marital stat,major industry code,major occupation code,race,hispanic origin,sex,member of a labor union,reason for unemployment,full or part time employment stat,capital gains,capital losses,dividends from stocks,tax filer stat,region of previous residence,state of previous residence,detailed household and family stat,detailed household summary in household,weight,migration code-change in msa,migration code-change in reg,migration code-move within reg,live in this house 1 year ago,migration prev res in sunbelt,num persons worked for employer,family members under 18,country of birth father,country of birth mother,country of birth self,citizenship,own business or self employed,fill inc questionnaire for veteran's admin,veterans benefits,weeks worked in year,year,label
0,73,Not in universe,0,0,High school graduate,0,Not in universe,Widowed,Not in universe or children,Not in universe,White,All other,Female,Not in universe,Not in universe,Not in labor force,0,0,0,Nonfiler,Not in universe,Not in universe,Other Rel 18+ ever marr not in subfamily,Other relative of householder,1700.09,<NA>,<NA>,<NA>,Not in universe under 1 year old,<NA>,0,Not in universe,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,95,- 50000.
1,58,Self-employed-not incorporated,4,34,Some college but no degree,0,Not in universe,Divorced,Construction,Precision production craft & repair,White,All other,Male,Not in universe,Not in universe,Children or Armed Forces,0,0,0,Head of household,South,Arkansas,Householder,Householder,1053.55,MSA to MSA,Same county,Same county,No,Yes,1,Not in universe,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,- 50000.
2,18,Not in universe,0,0,10th grade,0,High school,Never married,Not in universe or children,Not in universe,Asian or Pacific Islander,All other,Female,Not in universe,Not in universe,Not in labor force,0,0,0,Nonfiler,Not in universe,Not in universe,Child 18+ never marr Not in a subfamily,Child 18 or older,991.95,<NA>,<NA>,<NA>,Not in universe under 1 year old,<NA>,0,Not in universe,Vietnam,Vietnam,Vietnam,Foreign born- Not a citizen of U S,0,Not in universe,2,0,95,- 50000.
3,9,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,White,All other,Female,Not in universe,Not in universe,Children or Armed Forces,0,0,0,Nonfiler,Not in universe,Not in universe,Child <18 never marr not in subfamily,Child under 18 never married,1758.14,Nonmover,Nonmover,Nonmover,Yes,Not in universe,0,Both parents present,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,- 50000.
4,10,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,White,All other,Female,Not in universe,Not in universe,Children or Armed Forces,0,0,0,Nonfiler,Not in universe,Not in universe,Child <18 never marr not in subfamily,Child under 18 never married,1069.16,Nonmover,Nonmover,Nonmover,Yes,Not in universe,0,Both parents present,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,- 50000.

In [7]:
missing_check = (
    df_clean.isna()
    .sum()
    .rename("missing_count")
    .to_frame()
)
missing_check["missing_rate"] = missing_check["missing_count"] / len(df_clean)
missing_check.sort_values("missing_count", ascending=False).head(15)

                                missing_count  missing_rate
migration prev res in sunbelt           99696      0.499672
migration code-change in msa            99696      0.499672
migration code-change in reg            99696      0.499672
migration code-move within reg          99696      0.499672
country of birth father                  6713      0.033645
country of birth mother                  6119      0.030668
country of birth self                    3393      0.017006
hispanic origin                           874      0.004380
state of previous residence               708      0.003548
age                                         0      0.000000
major occupation code                       0      0.000000
major industry code                         0      0.000000
marital stat                                0      0.000000
enroll in edu inst last wk                  0      0.000000
wage per hour                               0      0.000000

In [8]:
label_counts = df_clean["label"].value_counts(dropna=False).rename("row_count").to_frame()
label_counts["row_share"] = label_counts["row_count"] / len(df_clean)
label_counts

          row_count  row_share
label
- 50000.     187141   0.937942
50000+.       12382   0.062058

In [9]:
weighted_label_counts = df_clean.groupby("label", dropna=False)["weight"].sum().rename("weighted_count").to_frame()
weighted_label_counts["weighted_share"] = weighted_label_counts["weighted_count"] / weighted_label_counts["weighted_count"].sum()
weighted_label_counts

          weighted_count  weighted_share
label
- 50000.    3.250046e+08         0.93595
50000+.     2.224125e+07         0.06405

In [10]:
for col in ["age", "education", "class of worker", "sex", "major occupation code", "weeks worked in year", "year"]:
    print(f"\n{col}")
    display(df_clean[col].value_counts(dropna=False).head(15))

age

age
34    3489
35    3450
36    3353
31    3351
33    3340
5     3332
4     3318
3     3279
37    3278
38    3277
2     3236
7     3218
30    3203
32    3188
8     3187
Name: count, dtype: int64

education

education
High school graduate                      48407
Children                                  47422
Some college but no degree                27820
Bachelors degree(BA AB BS)                19865
7th and 8th grade                          8007
10th grade                                 7557
11th grade                                 6876
Masters degree(MA MS MEng MEd MSW MBA)     6541
9th grade                                  6230
Associates degree-occup /vocational        5358
Associates degree-academic program         4363
5th or 6th grade                           3277
12th grade no diploma                      2126
1st 2nd 3rd or 4th grade                   1799
Prof school degree (MD DDS DVM LLB JD)     1793
Name: count, dtype: int64

class of worker

class of worker
Not in universe                   100245
Private                            72028
Self-employed-not incorporated      8445
Local government                    7784
State government                    4227
Self-employed-incorporated          3265
Federal government                  2925
Never worked                         439
Without pay                          165
Name: count, dtype: int64

sex

sex
Female    103984
Male       95539
Name: count, dtype: int64

major occupation code

major occupation code
Not in universe                          100684
Adm support including clerical            14837
Professional specialty                    13940
Executive admin and managerial            12495
Other service                             12099
Sales                                     11783
Precision production craft & repair       10518
Machine operators assmblrs & inspctrs      6379
Handlers equip cleaners etc                4127
Transportation and material moving         4020
Farming forestry and fishing               3146
Technicians and related support            3018
Protective services                        1661
Private household services                  780
Armed Forces                                 36
Name: count, dtype: int64

weeks worked in year

weeks worked in year
0     95983
52    70314
40     2790
50     2304
26     2268
48     1806
12     1780
30     1378
20     1330
8      1126
36     1108
16      945
32      883
44      845
51      819
Name: count, dtype: int64

year

year
94    99827
95    99696
Name: count, dtype: int64

In [11]:
age_distribution = df_clean["age"].value_counts().sort_index().rename_axis("age").reset_index(name="row_count")
age_distribution["row_share"] = age_distribution["row_count"] / len(df_clean)

age_income_rate = df_clean.groupby("age")["label"].apply(lambda x: x.str.contains("+", regex=False).mean()).rename("high_income_rate").reset_index()
age_distribution = age_distribution.merge(age_income_rate, on="age", how="left")

print("Age summary:")
display(df_clean["age"].describe())

print("Age distribution and high-income rate by exact age:")
display(age_distribution)

Age summary:

count    199523.000000
mean         34.494199
std          22.310895
min           0.000000
25%          15.000000
50%          33.000000
75%          50.000000
max          90.000000
Name: age, dtype: float64

Age distribution and high-income rate by exact age:

    age  row_count  row_share  high_income_rate
0     0       2839   0.014229          0.000000
1     1       3138   0.015728          0.000000
2     2       3236   0.016219          0.000000
3     3       3279   0.016434          0.000000
4     4       3318   0.016630          0.000000
..  ...        ...        ...               ...
86   86        348   0.001744          0.020115
87   87        301   0.001509          0.016611
88   88        241   0.001208          0.020747
89   89        195   0.000977          0.015385
90   90        725   0.003634          0.031724

[91 rows x 4 columns]

In [12]:
weeks_distribution = df_clean["weeks worked in year"].value_counts().sort_index().rename_axis("weeks worked in year").reset_index(name="row_count")
weeks_distribution["row_share"] = weeks_distribution["row_count"] / len(df_clean)

weeks_income_rate = df_clean.groupby("weeks worked in year")["label"].apply(lambda x: x.str.contains("+", regex=False).mean()).rename("high_income_rate").reset_index()
weeks_distribution = weeks_distribution.merge(weeks_income_rate, on="weeks worked in year", how="left")

print("Weeks worked summary:")
display(df_clean["weeks worked in year"].describe())

print("Weeks worked distribution and high-income rate by exact value:")
display(weeks_distribution)

Weeks worked summary:

count    199523.000000
mean         23.174897
std          24.411488
min           0.000000
25%           0.000000
50%           8.000000
75%          52.000000
max          52.000000
Name: weeks worked in year, dtype: float64

Weeks worked distribution and high-income rate by exact value:

    weeks worked in year  row_count  row_share  high_income_rate
0                      0      95983   0.481062          0.006209
1                      1        464   0.002326          0.017241
2                      2        458   0.002295          0.010917
3                      3        417   0.002090          0.019185
4                      4        757   0.003794          0.009247
5                      5        309   0.001549          0.009709
6                      6        646   0.003238          0.003096
7                      7        152   0.000762          0.026316
8                      8       1126   0.005643          0.009769
9                      9        239   0.001198          0.025105
10                    10        694   0.003478          0.011527
11                    11         78   0.000391          0.038462
12                    12       1780   0.008921          0.008427
13                    13        496   0.002486          0.018145
14                    14        257   0.001288          0.015564
15                    15        353   0.001769          0.025496
16                    16        945   0.004736          0.011640
17                    17        331   0.001659          0.021148
18                    18        272   0.001363          0.011029
19                    19         48   0.000241          0.041667
20                    20       1330   0.006666          0.015038
21                    21        135   0.000677          0.044444
22                    22        370   0.001854          0.018919
23                    23         67   0.000336          0.000000
24                    24        767   0.003844          0.023468
25                    25        457   0.002290          0.010941
26                    26       2268   0.011367          0.032187
27                    27         76   0.000381          0.026316
28                    28        568   0.002847          0.036972
29                    29         63   0.000316          0.063492
30                    30       1378   0.006906          0.030479
31                    31         51   0.000256          0.039216
32                    32        883   0.004426          0.031710
33                    33         81   0.000406          0.049383
34                    34        230   0.001153          0.056522
35                    35        704   0.003528          0.036932
36                    36       1108   0.005553          0.038809
37                    37        123   0.000616          0.065041
38                    38        380   0.001905          0.039474
39                    39        602   0.003017          0.044850
40                    40       2790   0.013983          0.050896
41                    41         88   0.000441          0.079545
42                    42        573   0.002872          0.041885
43                    43        374   0.001874          0.042781
44                    44        845   0.004235          0.047337
45                    45        669   0.003353          0.056801
46                    46        708   0.003548          0.088983
47                    47        278   0.001393          0.043165
48                    48       1806   0.009052          0.086932
49                    49        509   0.002551          0.106090
50                    50       2304   0.011548          0.107205
51                    51        819   0.004105          0.109890
52                    52      70314   0.352410          0.148008

## 8. Add Simple EDA Columns

These are just simple helper columns for understanding the data. They are not modeling features yet.

In [13]:
df_clean["income_over_50k"] = df_clean["label"].str.contains("+", regex=False).astype(int)

df_clean["age_bucket"] = pd.cut(
    df_clean["age"],
    bins=[-1, 17, 24, 34, 44, 54, 64, 120],
    labels=["0-17", "18-24", "25-34", "35-44", "45-54", "55-64", "65+"],
)

df_clean["weeks_worked_bucket"] = pd.cut(
    df_clean["weeks worked in year"],
    bins=[-1, 0, 13, 26, 51, 52],
    labels=["0", "1-13", "14-26", "27-51", "52"],
)

df_clean["is_adult"] = df_clean["age"] >= 18
df_clean["worked_any_weeks"] = df_clean["weeks worked in year"] > 0
df_clean["worked_full_year"] = df_clean["weeks worked in year"] == 52

df_clean[["label", "income_over_50k", "age", "age_bucket", "weeks worked in year", "weeks_worked_bucket", "is_adult", "worked_any_weeks", "worked_full_year"]].head()

,label,income_over_50k,age,age_bucket,weeks worked in year,weeks_worked_bucket,is_adult,worked_any_weeks,worked_full_year
0,- 50000.,0,73,65+,0,0,True,False,False
1,- 50000.,0,58,55-64,52,52,True,True,True
2,- 50000.,0,18,18-24,0,0,True,False,False
3,- 50000.,0,9,0-17,0,0,False,False,False
4,- 50000.,0,10,0-17,0,0,False,False,False

In [14]:
def summarize_by_group(data, group_col):
    temp = data.copy()
    temp["weighted_high_income"] = temp["income_over_50k"] * temp["weight"]

    summary = temp.groupby(group_col, dropna=False).agg(
        row_count=("income_over_50k", "size"),
        high_income_count=("income_over_50k", "sum"),
        weighted_count=("weight", "sum"),
        weighted_high_income=("weighted_high_income", "sum"),
    )

    summary["row_share"] = summary["row_count"] / len(temp)
    summary["high_income_rate"] = summary["high_income_count"] / summary["row_count"]
    summary["weighted_share"] = summary["weighted_count"] / temp["weight"].sum()
    summary["weighted_high_income_rate"] = summary["weighted_high_income"] / summary["weighted_count"]

    return summary.sort_values("row_count", ascending=False)

summarize_by_group(df_clean, "label")

,row_count,high_income_count,weighted_count,weighted_high_income,row_share,high_income_rate,weighted_share,weighted_high_income_rate
label,,,,,,,,
- 50000.,187141,0,3.250046e+08,0.00,0.937942,0.0,0.93595,0.0
50000+.,12382,12382,2.224125e+07,22241245.25,0.062058,1.0,0.06405,1.0

In [15]:
for col in ["age_bucket", "weeks_worked_bucket", "is_adult", "worked_any_weeks", "worked_full_year"]:
    print(f"\n{col}")
    display(summarize_by_group(df_clean, col))

age_bucket

/tmp/ipykernel_8275/2182529189.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  summary = temp.groupby(group_col, dropna=False).agg(

,row_count,high_income_count,weighted_count,weighted_high_income,row_share,high_income_rate,weighted_share,weighted_high_income_rate
age_bucket,,,,,,,,
0-17,55992,2,93724255.85,3516.98,0.280629,0.000036,0.269907,0.000038
35-44,31420,3992,55773255.07,7243835.09,0.157476,0.127053,0.160616,0.129880
25-34,30889,1798,55556194.05,3266549.11,0.154814,0.058208,0.159991,0.058797
65+,24289,945,41001216.31,1660125.47,0.121735,0.038907,0.118075,0.040490
45-54,23199,3768,40112206.79,6754128.39,0.116272,0.162421,0.115515,0.168381
18-24,17824,111,33517693.01,192201.25,0.089333,0.006228,0.096524,0.005734
55-64,15910,1766,27561071.39,3120888.96,0.079740,0.110999,0.079370,0.113235

weeks_worked_bucket

/tmp/ipykernel_8275/2182529189.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  summary = temp.groupby(group_col, dropna=False).agg(

,row_count,high_income_count,weighted_count,weighted_high_income,row_share,high_income_rate,weighted_share,weighted_high_income_rate
weeks_worked_bucket,,,,,,,,
0,95983,596,1.636911e+08,1042353.45,0.481062,0.006209,0.471398,0.006368
52,70314,10407,1.244437e+08,18780757.64,0.352410,0.148008,0.358373,0.150918
27-51,18010,1125,3.184010e+07,1969532.20,0.090265,0.062465,0.091693,0.061857
1-13,7616,89,1.345071e+07,157456.07,0.038171,0.011686,0.038735,0.011706
14-26,7600,165,1.382033e+07,291145.89,0.038091,0.021711,0.039800,0.021066

is_adult

,row_count,high_income_count,weighted_count,weighted_high_income,row_share,high_income_rate,weighted_share,weighted_high_income_rate
is_adult,,,,,,,,
True,143531,12380,2.535216e+08,22237728.27,0.719371,0.086253,0.730093,0.087715
False,55992,2,9.372426e+07,3516.98,0.280629,0.000036,0.269907,0.000038

worked_any_weeks

,row_count,high_income_count,weighted_count,weighted_high_income,row_share,high_income_rate,weighted_share,weighted_high_income_rate
worked_any_weeks,,,,,,,,
True,103540,11786,1.835548e+08,21198891.80,0.518938,0.113830,0.528602,0.115491
False,95983,596,1.636911e+08,1042353.45,0.481062,0.006209,0.471398,0.006368

worked_full_year

,row_count,high_income_count,weighted_count,weighted_high_income,row_share,high_income_rate,weighted_share,weighted_high_income_rate
worked_full_year,,,,,,,,
False,129209,1975,2.228022e+08,3460487.61,0.64759,0.015285,0.641627,0.015532
True,70314,10407,1.244437e+08,18780757.64,0.35241,0.148008,0.358373,0.150918

In [16]:
for col in ["education", "class of worker", "marital stat", "major occupation code", "full or part time employment stat"]:
    print(f"\n{col}")
    display(summarize_by_group(df_clean, col).head(15))

education

,row_count,high_income_count,weighted_count,weighted_high_income,row_share,high_income_rate,weighted_share,weighted_high_income_rate
education,,,,,,,,
High school graduate,48407,1879,85589219.42,3220021.57,0.242614,0.038817,0.246480,0.037622
Children,47422,0,79104048.39,0.00,0.237677,0.000000,0.227804,0.000000
Some college but no degree,27820,1787,50296154.39,3267066.76,0.139433,0.064234,0.144843,0.064957
Bachelors degree(BA AB BS),19865,3915,35738476.21,7271835.12,0.099562,0.197080,0.102920,0.203474
7th and 8th grade,8007,72,13126143.41,116019.01,0.040131,0.008992,0.037801,0.008839
10th grade,7557,62,13272987.31,110725.73,0.037875,0.008204,0.038224,0.008342
11th grade,6876,70,12290046.29,126722.95,0.034462,0.010180,0.035393,0.010311
Masters degree(MA MS MEng MEd MSW MBA),6541,2038,11475673.95,3625738.38,0.032783,0.311573,0.033048,0.315950
9th grade,6230,38,10520947.09,62717.71,0.031224,0.006100,0.030298,0.005961
Associates degree-occup /vocational,5358,413,9186755.06,697604.61,0.026854,0.077081,0.026456,0.075936
Associates degree-academic program,4363,412,7923965.51,763264.50,0.021867,0.094430,0.022819,0.096324
5th or 6th grade,3277,22,5178876.45,33458.23,0.016424,0.006713,0.014914,0.006461
12th grade no diploma,2126,34,3760879.44,55714.06,0.010655,0.015992,0.010831,0.014814
1st 2nd 3rd or 4th grade,1799,13,2937692.92,18831.72,0.009017,0.007226,0.008460,0.006410
Prof school degree (MD DDS DVM LLB JD),1793,969,3155198.08,1700410.04,0.008986,0.540435,0.009086,0.538923

class of worker

,row_count,high_income_count,weighted_count,weighted_high_income,row_share,high_income_rate,weighted_share,weighted_high_income_rate
class of worker,,,,,,,,
Not in universe,100245,904,1.708704e+08,1606443.70,0.502423,0.009018,0.492073,0.009402
Private,72028,7322,1.291665e+08,13205254.21,0.361001,0.101655,0.371974,0.102234
Self-employed-not incorporated,8445,1090,1.451549e+07,1929409.49,0.042326,0.129070,0.041802,0.132921
Local government,7784,847,1.374835e+07,1542444.45,0.039013,0.108813,0.039593,0.112191
State government,4227,485,7.165721e+06,839995.19,0.021186,0.114739,0.020636,0.117224
Self-employed-incorporated,3265,1134,5.652140e+06,2049705.88,0.016364,0.347320,0.016277,0.362642
Federal government,2925,597,5.053904e+06,1065127.09,0.014660,0.204103,0.014554,0.210753
Never worked,439,2,8.076583e+05,2373.97,0.002200,0.004556,0.002326,0.002939
Without pay,165,1,2.657429e+05,491.27,0.000827,0.006061,0.000765,0.001849

marital stat

,row_count,high_income_count,weighted_count,weighted_high_income,row_share,high_income_rate,weighted_share,weighted_high_income_rate
marital stat,,,,,,,,
Never married,86485,1117,1.519181e+08,2075191.22,0.433459,0.012916,0.437494,0.013660
Married-civilian spouse present,84222,9600,1.444042e+08,17234551.75,0.422117,0.113984,0.415856,0.119349
Divorced,12710,1066,2.317747e+07,1869874.30,0.063702,0.083871,0.066747,0.080676
Widowed,10463,330,1.754912e+07,561114.14,0.052440,0.031540,0.050538,0.031974
Separated,3460,158,6.448192e+06,324806.53,0.017341,0.045665,0.018570,0.050372
Married-spouse absent,1518,96,2.648742e+06,148259.46,0.007608,0.063241,0.007628,0.055974
Married-A F spouse present,665,15,1.100045e+06,27447.85,0.003333,0.022556,0.003168,0.024952

major occupation code

,row_count,high_income_count,weighted_count,weighted_high_income,row_share,high_income_rate,weighted_share,weighted_high_income_rate
major occupation code,,,,,,,,
Not in universe,100684,906,1.716781e+08,1608817.67,0.504624,0.008998,0.494399,0.009371
Adm support including clerical,14837,446,2.635368e+07,797493.85,0.074362,0.030060,0.075893,0.030261
Professional specialty,13940,3475,2.461443e+07,6255581.25,0.069867,0.249283,0.070885,0.254143
Executive admin and managerial,12495,3593,2.219117e+07,6447795.63,0.062624,0.287555,0.063906,0.290557
Other service,12099,120,2.096747e+07,211620.01,0.060640,0.009918,0.060382,0.010093
Sales,11783,1524,2.121534e+07,2814554.91,0.059056,0.129339,0.061096,0.132666
Precision production craft & repair,10518,955,1.884325e+07,1674603.24,0.052716,0.090797,0.054265,0.088870
Machine operators assmblrs & inspctrs,6379,235,1.133860e+07,433775.63,0.031971,0.036840,0.032653,0.038257
Handlers equip cleaners etc,4127,79,7.580926e+06,136049.72,0.020684,0.019142,0.021832,0.017946
Transportation and material moving,4020,259,7.265852e+06,464354.23,0.020148,0.064428,0.020924,0.063909
Farming forestry and fishing,3146,160,5.177166e+06,225194.75,0.015768,0.050858,0.014909,0.043498
Technicians and related support,3018,361,5.460453e+06,654908.45,0.015126,0.119616,0.015725,0.119937
Protective services,1661,259,3.179314e+06,498397.39,0.008325,0.155930,0.009156,0.156763
Private household services,780,2,1.311144e+06,4309.96,0.003909,0.002564,0.003776,0.003287
Armed Forces,36,8,6.901379e+04,13788.56,0.000180,0.222222,0.000199,0.199794

full or part time employment stat

,row_count,high_income_count,weighted_count,weighted_high_income,row_share,high_income_rate,weighted_share,weighted_high_income_rate
full or part time employment stat,,,,,,,,
Children or Armed Forces,123769,5874,2.129070e+08,10533037.48,0.620324,0.047459,0.613130,0.049472
Full-time schedules,40736,5366,7.263862e+07,9684929.01,0.204167,0.131726,0.209185,0.133330
Not in labor force,26808,462,4.684131e+07,814064.16,0.134360,0.017234,0.134894,0.017379
PT for non-econ reasons usually FT,3322,393,5.997410e+06,691619.04,0.016650,0.118302,0.017271,0.115320
Unemployed full-time,2311,83,4.214827e+06,142268.05,0.011583,0.035915,0.012138,0.033754
PT for econ reasons usually PT,1209,155,2.160595e+06,280205.95,0.006059,0.128205,0.006222,0.129689
Unemployed part- time,843,18,1.535414e+06,32294.37,0.004225,0.021352,0.004422,0.021033
PT for econ reasons usually FT,525,31,9.507238e+05,62827.19,0.002631,0.059048,0.002738,0.066084

In [17]:
adult_workers = df_clean[(df_clean["is_adult"]) & (df_clean["worked_any_weeks"])].copy()

print(f"All rows: {len(df_clean):,}")
print(f"Adult workers: {len(adult_workers):,}")
print(f"Share of rows that are adult workers: {len(adult_workers) / len(df_clean):.2%}")

display(summarize_by_group(df_clean, "label"))
display(summarize_by_group(adult_workers, "label"))

All rows: 199,523
Adult workers: 100,445
Share of rows that are adult workers: 50.34%

,row_count,high_income_count,weighted_count,weighted_high_income,row_share,high_income_rate,weighted_share,weighted_high_income_rate
label,,,,,,,,
- 50000.,187141,0,3.250046e+08,0.00,0.937942,0.0,0.93595,0.0
50000+.,12382,12382,2.224125e+07,22241245.25,0.062058,1.0,0.06405,1.0

,row_count,high_income_count,weighted_count,weighted_high_income,row_share,high_income_rate,weighted_share,weighted_high_income_rate
label,,,,,,,,
- 50000.,88661,0,1.572168e+08,0.00,0.882682,0.0,0.8812,0.0
50000+.,11784,11784,2.119537e+07,21195374.82,0.117318,1.0,0.1188,1.0

In [18]:
# Install stronger boosting libraries in the Colab runtime before running the classification models.
!pip install -q xgboost lightgbm

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.dummy import DummyClassifier
from sklearn.ensemble import ExtraTreesClassifier, RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score, precision_score, recall_score, roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.tree import DecisionTreeClassifier

RANDOM_STATE = 42

In [20]:
model_data = df_clean.where(pd.notna(df_clean), np.nan).copy()

# Use the original census variables as model inputs. Do not use label, weight, or EDA helper columns as predictors.
feature_cols = [col for col in column_names if col not in ["label", "weight"]]

# A few numeric columns are really codes/categories, not continuous measurements.
code_like_cols = [
    "detailed industry recode",
    "detailed occupation recode",
    "own business or self employed",
    "veterans benefits",
    "year",
]
code_like_cols = [col for col in code_like_cols if col in feature_cols]

numeric_features = model_data[feature_cols].select_dtypes(include=np.number).columns.tolist()
numeric_features = [col for col in numeric_features if col not in code_like_cols]

categorical_features = [col for col in feature_cols if col not in numeric_features]

for col in categorical_features:
    model_data[col] = model_data[col].astype("string").fillna("Missing")

X = model_data[feature_cols]
y = model_data["income_over_50k"]
sample_weight = model_data["weight"]

print(f"Features: {len(feature_cols)}")
print(f"Numeric features: {len(numeric_features)}")
print(f"Categorical features: {len(categorical_features)}")

Features: 40
Numeric features: 7
Categorical features: 33

In [21]:
def make_one_hot_encoder():
    try:
        return OneHotEncoder(handle_unknown="ignore", sparse_output=True)
    except TypeError:
        return OneHotEncoder(handle_unknown="ignore", sparse=True)

def make_preprocessor():
    numeric_pipeline = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler()),
    ])

    categorical_pipeline = Pipeline([
        ("imputer", SimpleImputer(strategy="constant", fill_value="Missing")),
        ("onehot", make_one_hot_encoder()),
    ])

    return ColumnTransformer([
        ("num", numeric_pipeline, numeric_features),
        ("cat", categorical_pipeline, categorical_features),
    ])

In [22]:
X_train, X_test, y_train, y_test, w_train, w_test = train_test_split(
    X,
    y,
    sample_weight,
    test_size=0.25,
    random_state=RANDOM_STATE,
    stratify=y,
)

print(f"Train rows: {len(X_train):,}")
print(f"Test rows: {len(X_test):,}")
print(y_train.value_counts(normalize=True))

Train rows: 149,642
Test rows: 49,881
income_over_50k
0    0.937945
1    0.062055
Name: proportion, dtype: float64

In [23]:
from sklearn.ensemble import ExtraTreesClassifier, RandomForestClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier

positive_train_weight = w_train[y_train == 1].sum()
negative_train_weight = w_train[y_train == 0].sum()
scale_pos_weight = negative_train_weight / positive_train_weight

primary_classification_models = {
    "dummy_baseline": Pipeline([
        ("preprocess", make_preprocessor()),
        ("model", DummyClassifier(strategy="most_frequent")),
    ]),
    "logistic_regression": Pipeline([
        ("preprocess", make_preprocessor()),
        ("model", LogisticRegression(max_iter=1000, class_weight="balanced", random_state=RANDOM_STATE)),
    ]),
    "shallow_decision_tree": Pipeline([
        ("preprocess", make_preprocessor()),
        ("model", DecisionTreeClassifier(max_depth=6, min_samples_leaf=200, class_weight="balanced", random_state=RANDOM_STATE)),
    ]),
    "random_forest": Pipeline([
        ("preprocess", make_preprocessor()),
        ("model", RandomForestClassifier(
            n_estimators=200,
            min_samples_leaf=50,
            class_weight="balanced_subsample",
            n_jobs=-1,
            random_state=RANDOM_STATE,
        )),
    ]),
    "xgboost_unweighted": Pipeline([
        ("preprocess", make_preprocessor()),
        ("model", XGBClassifier(
            n_estimators=300,
            learning_rate=0.05,
            max_depth=4,
            subsample=0.8,
            colsample_bytree=0.8,
            objective="binary:logistic",
            eval_metric="auc",
            tree_method="hist",
            n_jobs=-1,
            random_state=RANDOM_STATE,
        )),
    ]),
    "lightgbm_unweighted": Pipeline([
        ("preprocess", make_preprocessor()),
        ("model", LGBMClassifier(
            n_estimators=400,
            learning_rate=0.03,
            num_leaves=31,
            subsample=0.8,
            colsample_bytree=0.8,
            n_jobs=-1,
            random_state=RANDOM_STATE,
            verbose=-1,
        )),
    ]),
}

challenger_classification_models = {
    "extra_trees": Pipeline([
        ("preprocess", make_preprocessor()),
        ("model", ExtraTreesClassifier(
            n_estimators=300,
            min_samples_leaf=50,
            class_weight="balanced_subsample",
            n_jobs=-1,
            random_state=RANDOM_STATE,
        )),
    ]),
    "xgboost_balanced": Pipeline([
        ("preprocess", make_preprocessor()),
        ("model", XGBClassifier(
            n_estimators=300,
            learning_rate=0.05,
            max_depth=4,
            subsample=0.8,
            colsample_bytree=0.8,
            scale_pos_weight=scale_pos_weight,
            objective="binary:logistic",
            eval_metric="auc",
            tree_method="hist",
            n_jobs=-1,
            random_state=RANDOM_STATE,
        )),
    ]),
    "lightgbm_balanced": Pipeline([
        ("preprocess", make_preprocessor()),
        ("model", LGBMClassifier(
            n_estimators=400,
            learning_rate=0.03,
            num_leaves=31,
            subsample=0.8,
            colsample_bytree=0.8,
            scale_pos_weight=scale_pos_weight,
            n_jobs=-1,
            random_state=RANDOM_STATE,
            verbose=-1,
        )),
    ]),
    "xgboost_tuned": Pipeline([
        ("preprocess", make_preprocessor()),
        ("model", XGBClassifier(
            n_estimators=500,
            learning_rate=0.03,
            max_depth=5,
            min_child_weight=5,
            subsample=0.85,
            colsample_bytree=0.85,
            objective="binary:logistic",
            eval_metric="auc",
            tree_method="hist",
            n_jobs=-1,
            random_state=RANDOM_STATE,
        )),
    ]),
    "lightgbm_tuned": Pipeline([
        ("preprocess", make_preprocessor()),
        ("model", LGBMClassifier(
            n_estimators=700,
            learning_rate=0.02,
            num_leaves=63,
            min_child_samples=100,
            subsample=0.85,
            colsample_bytree=0.85,
            n_jobs=-1,
            random_state=RANDOM_STATE,
            verbose=-1,
        )),
    ]),
}

classification_models = {**primary_classification_models, **challenger_classification_models}
model_groups = {
    **{name: "primary" for name in primary_classification_models},
    **{name: "challenger" for name in challenger_classification_models},
}

pd.DataFrame({
    "model": list(classification_models.keys()),
    "comparison_group": [model_groups[name] for name in classification_models],
})

                    model comparison_group
0          dummy_baseline          primary
1     logistic_regression          primary
2   shallow_decision_tree          primary
3           random_forest          primary
4      xgboost_unweighted          primary
5     lightgbm_unweighted          primary
6             extra_trees       challenger
7        xgboost_balanced       challenger
8       lightgbm_balanced       challenger
9           xgboost_tuned       challenger
10         lightgbm_tuned       challenger

In [24]:
def evaluate_classifier(name, model):
    pred = model.predict(X_test)
    prob = model.predict_proba(X_test)[:, 1]

    return {
        "comparison_group": model_groups[name],
        "model": name,
        "accuracy": accuracy_score(y_test, pred, sample_weight=w_test),
        "precision": precision_score(y_test, pred, sample_weight=w_test, zero_division=0),
        "recall": recall_score(y_test, pred, sample_weight=w_test, zero_division=0),
        "f1": f1_score(y_test, pred, sample_weight=w_test, zero_division=0),
        "roc_auc": roc_auc_score(y_test, prob, sample_weight=w_test),
    }

fitted_classifiers = {}
classification_results = []

for name, model in classification_models.items():
    print(f"Training {name}...")
    model.fit(X_train, y_train, model__sample_weight=w_train)
    fitted_classifiers[name] = model
    classification_results.append(evaluate_classifier(name, model))

model_comparison = pd.DataFrame(classification_results)
model_comparison["marketing_selection_metric"] = model_comparison["f1"]
model_comparison = model_comparison.sort_values(["marketing_selection_metric", "roc_auc"], ascending=False)
model_comparison[["comparison_group", "model", "marketing_selection_metric", "roc_auc", "f1", "precision", "recall", "accuracy"]]

Training dummy_baseline...
Training logistic_regression...
Training shallow_decision_tree...
Training random_forest...
Training xgboost_unweighted...
Training lightgbm_unweighted...

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

Training extra_trees...
Training xgboost_balanced...
Training lightgbm_balanced...

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

Training xgboost_tuned...
Training lightgbm_tuned...

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

,comparison_group,model,marketing_selection_metric,roc_auc,f1,precision,recall,accuracy
10,challenger,lightgbm_tuned,0.601014,0.954432,0.601014,0.754484,0.499425,0.957150
5,primary,lightgbm_unweighted,0.591254,0.954593,0.591254,0.763869,0.482272,0.956909
9,challenger,xgboost_tuned,0.572724,0.953930,0.572724,0.774013,0.454521,0.956174
4,primary,xgboost_unweighted,0.557527,0.952535,0.557527,0.773169,0.435940,0.955285
8,challenger,lightgbm_balanced,0.483817,0.954659,0.483817,0.331573,0.894560,0.876649
7,challenger,xgboost_balanced,0.462415,0.951924,0.462415,0.311533,0.896711,0.865266
1,primary,logistic_regression,0.445895,0.946054,0.445895,0.296553,0.898251,0.855733
3,primary,random_forest,0.417025,0.941357,0.417025,0.271405,0.899808,0.837427
6,challenger,extra_trees,0.386930,0.931968,0.386930,0.247340,0.888191,0.818116
2,primary,shallow_decision_tree,0.365065,0.912099,0.365065,0.228841,0.902013,0.797240
0,primary,dummy_baseline,0.000000,0.500000,0.000000,0.000000,0.000000,0.935378

In [25]:
model_comparison[["comparison_group", "model", "marketing_selection_metric", "roc_auc", "f1", "precision", "recall", "accuracy"]].round(4)

,comparison_group,model,marketing_selection_metric,roc_auc,f1,precision,recall,accuracy
10,challenger,lightgbm_tuned,0.6010,0.9544,0.6010,0.7545,0.4994,0.9571
5,primary,lightgbm_unweighted,0.5913,0.9546,0.5913,0.7639,0.4823,0.9569
9,challenger,xgboost_tuned,0.5727,0.9539,0.5727,0.7740,0.4545,0.9562
4,primary,xgboost_unweighted,0.5575,0.9525,0.5575,0.7732,0.4359,0.9553
8,challenger,lightgbm_balanced,0.4838,0.9547,0.4838,0.3316,0.8946,0.8766
7,challenger,xgboost_balanced,0.4624,0.9519,0.4624,0.3115,0.8967,0.8653
1,primary,logistic_regression,0.4459,0.9461,0.4459,0.2966,0.8983,0.8557
3,primary,random_forest,0.4170,0.9414,0.4170,0.2714,0.8998,0.8374
6,challenger,extra_trees,0.3869,0.9320,0.3869,0.2473,0.8882,0.8181
2,primary,shallow_decision_tree,0.3651,0.9121,0.3651,0.2288,0.9020,0.7972
0,primary,dummy_baseline,0.0000,0.5000,0.0000,0.0000,0.0000,0.9354

In [26]:
def best_row(metric):
    row = model_comparison.loc[model_comparison[metric].idxmax()].to_dict()
    row["selection_metric"] = metric
    return row

marketing_row = model_comparison.iloc[0].to_dict()
marketing_row["selection_metric"] = "marketing_rule_f1_then_auc"

best_by_metric = pd.DataFrame([
    marketing_row,
    best_row("roc_auc"),
    best_row("f1"),
    best_row("accuracy"),
])[["selection_metric", "comparison_group", "model", "roc_auc", "f1", "precision", "recall", "accuracy"]]

best_by_metric.round(4)

,selection_metric,comparison_group,model,roc_auc,f1,precision,recall,accuracy
0,marketing_rule_f1_then_auc,challenger,lightgbm_tuned,0.9544,0.6010,0.7545,0.4994,0.9571
1,roc_auc,challenger,lightgbm_balanced,0.9547,0.4838,0.3316,0.8946,0.8766
2,f1,challenger,lightgbm_tuned,0.9544,0.6010,0.7545,0.4994,0.9571
3,accuracy,challenger,lightgbm_tuned,0.9544,0.6010,0.7545,0.4994,0.9571

In [27]:
best_classifier_name = model_comparison.iloc[0]["model"]
best_classifier = fitted_classifiers[best_classifier_name]

print(f"Selected model for retail marketing by F1, with ROC AUC as tie-breaker: {best_classifier_name}")
model_comparison.iloc[[0]][["comparison_group", "model", "roc_auc", "f1", "precision", "recall", "accuracy"]].round(4)

Selected model for retail marketing by F1, with ROC AUC as tie-breaker: lightgbm_tuned

,comparison_group,model,roc_auc,f1,precision,recall,accuracy
10,challenger,lightgbm_tuned,0.9544,0.601,0.7545,0.4994,0.9571

In [28]:
best_classifier_prob = best_classifier.predict_proba(X_test)[:, 1]
best_classifier_auc = roc_auc_score(y_test, best_classifier_prob, sample_weight=w_test)

threshold_rows = []
for threshold in np.arange(0.05, 0.96, 0.05):
    pred = (best_classifier_prob >= threshold).astype(int)
    threshold_rows.append({
        "threshold": threshold,
        "accuracy": accuracy_score(y_test, pred, sample_weight=w_test),
        "precision": precision_score(y_test, pred, sample_weight=w_test, zero_division=0),
        "recall": recall_score(y_test, pred, sample_weight=w_test, zero_division=0),
        "f1": f1_score(y_test, pred, sample_weight=w_test, zero_division=0),
        "roc_auc": best_classifier_auc,
        "weighted_predicted_positive_share": np.average(pred, weights=w_test),
    })

threshold_comparison = pd.DataFrame(threshold_rows)
threshold_comparison = threshold_comparison.sort_values(["f1", "precision"], ascending=False)

best_threshold = float(threshold_comparison.iloc[0]["threshold"])
best_threshold_metrics = threshold_comparison.iloc[[0]]

print(f"Best threshold for F1: {best_threshold:.2f}")
threshold_comparison.head(10).round(4)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

Best threshold for F1: 0.35

,threshold,accuracy,precision,recall,f1,roc_auc,weighted_predicted_positive_share
6,0.35,0.9540,0.6536,0.6132,0.6327,0.9544,0.0606
5,0.30,0.9513,0.6174,0.6478,0.6322,0.9544,0.0678
7,0.40,0.9555,0.6846,0.5776,0.6266,0.9544,0.0545
4,0.25,0.9467,0.5730,0.6903,0.6262,0.9544,0.0778
8,0.45,0.9567,0.7218,0.5368,0.6157,0.9544,0.0481
3,0.20,0.9397,0.5240,0.7322,0.6108,0.9544,0.0903
9,0.50,0.9571,0.7545,0.4994,0.6010,0.9544,0.0428
2,0.15,0.9273,0.4627,0.7794,0.5807,0.9544,0.1088
10,0.55,0.9570,0.7905,0.4559,0.5783,0.9544,0.0373
11,0.60,0.9560,0.8157,0.4129,0.5482,0.9544,0.0327

In [29]:
best_classifier_prob = best_classifier.predict_proba(X_test)[:, 1]
pred = (best_classifier_prob >= best_threshold).astype(int)
cm = confusion_matrix(y_test, pred, sample_weight=w_test)

print(f"Selected retail marketing classifier: {best_classifier_name}")
print(f"Selected threshold: {best_threshold:.2f}")
pd.DataFrame(
    cm,
    index=["actual_<=50k", "actual_>50k"],
    columns=["pred_<=50k", "pred_>50k"],
)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

Selected retail marketing classifier: lightgbm_tuned
Selected threshold: 0.35

               pred_<=50k   pred_>50k
actual_<=50k  79349184.01  1822689.96
actual_>50k    2169152.14  3438719.91

In [30]:
from sklearn.cluster import MiniBatchKMeans

# For marketing segmentation, start with adults. Children can be handled later as a separate household-level question.
segmentation_data = model_data[model_data["age"] >= 18].copy()

segment_preprocessor = make_preprocessor()
X_segment = segment_preprocessor.fit_transform(segmentation_data[feature_cols])

segment_model = MiniBatchKMeans(
    n_clusters=5,
    random_state=RANDOM_STATE,
    batch_size=4096,
    n_init=10,
)

segment_model.fit(X_segment, sample_weight=segmentation_data["weight"])
segmentation_data["segment"] = segment_model.labels_

segmentation_data["segment"].value_counts().sort_index()

segment
0     5806
1    23394
2    23332
3    44901
4    46098
Name: count, dtype: int64

In [31]:
def top_values(data, col, n=3):
    return ", ".join(data[col].astype("string").fillna("Missing").value_counts().head(n).index.tolist())

segment_rows = []

for segment, group in segmentation_data.groupby("segment"):
    weighted_count = group["weight"].sum()
    segment_rows.append({
        "segment": segment,
        "rows": len(group),
        "weighted_share": weighted_count / segmentation_data["weight"].sum(),
        "high_income_rate": group["income_over_50k"].mean(),
        "weighted_high_income_rate": (group["income_over_50k"] * group["weight"]).sum() / weighted_count,
        "avg_age": np.average(group["age"], weights=group["weight"]),
        "avg_weeks_worked": np.average(group["weeks worked in year"], weights=group["weight"]),
        "top_education": top_values(group, "education"),
        "top_class_of_worker": top_values(group, "class of worker"),
        "top_marital_stat": top_values(group, "marital stat"),
        "top_major_occupation": top_values(group, "major occupation code"),
    })

segment_profile = pd.DataFrame(segment_rows).sort_values("weighted_share", ascending=False)
segment_profile

,segment,rows,weighted_share,high_income_rate,weighted_high_income_rate,avg_age,avg_weeks_worked,top_education,top_class_of_worker,top_marital_stat,top_major_occupation
4,4,46098,0.321353,0.113823,0.115706,38.241076,45.559684,"High school graduate, Some college but no degree, Bachelors degree(BA AB BS)","Private, Self-employed-not incorporated, Local government","Married-civilian spouse present, Never married, Divorced","Adm support including clerical, Professional specialty, Executive admin and managerial"
3,3,44901,0.317023,0.130554,0.131334,38.627100,45.782142,"High school graduate, Some college but no degree, Bachelors degree(BA AB BS)","Private, Self-employed-not incorporated, Local government","Married-civilian spouse present, Never married, Divorced","Professional specialty, Adm support including clerical, Executive admin and managerial"
1,1,23394,0.161099,0.017269,0.017484,56.111722,2.396675,"High school graduate, Some college but no degree, 7th and 8th grade","Not in universe, Private, Self-employed-not incorporated","Married-civilian spouse present, Widowed, Never married","Not in universe, Other service, Farming forestry and fishing"
2,2,23332,0.159291,0.016544,0.016672,56.143989,1.933898,"High school graduate, Some college but no degree, 7th and 8th grade","Not in universe, Private, Self-employed-not incorporated","Married-civilian spouse present, Widowed, Never married","Not in universe, Other service, Adm support including clerical"
0,0,5806,0.041235,0.082845,0.083048,39.447012,48.603560,"High school graduate, Some college but no degree, Bachelors degree(BA AB BS)","Private, Local government, Federal government","Married-civilian spouse present, Never married, Divorced","Adm support including clerical, Precision production craft & repair, Professional specialty"

In [32]:
candidate_ks = [3, 4, 5, 6]
segment_profiles = {}
segment_model_rows = []

for k in candidate_ks:
    kmeans = MiniBatchKMeans(
        n_clusters=k,
        random_state=RANDOM_STATE,
        batch_size=4096,
        n_init=10,
    )
    kmeans.fit(X_segment, sample_weight=segmentation_data["weight"])

    temp = segmentation_data.copy()
    temp["segment"] = kmeans.labels_

    rows = []
    for segment, group in temp.groupby("segment"):
        weighted_count = group["weight"].sum()
        rows.append({
            "segment": segment,
            "rows": len(group),
            "weighted_share": weighted_count / temp["weight"].sum(),
            "weighted_high_income_rate": (group["income_over_50k"] * group["weight"]).sum() / weighted_count,
            "avg_age": np.average(group["age"], weights=group["weight"]),
            "avg_weeks_worked": np.average(group["weeks worked in year"], weights=group["weight"]),
            "top_education": top_values(group, "education"),
            "top_class_of_worker": top_values(group, "class of worker"),
            "top_marital_stat": top_values(group, "marital stat"),
            "top_major_occupation": top_values(group, "major occupation code"),
        })

    profile = pd.DataFrame(rows).sort_values("weighted_share", ascending=False)
    segment_profiles[k] = profile

    segment_model_rows.append({
        "k": k,
        "inertia": kmeans.inertia_,
        "smallest_weighted_segment_share": profile["weighted_share"].min(),
        "largest_weighted_segment_share": profile["weighted_share"].max(),
        "high_income_rate_range": profile["weighted_high_income_rate"].max() - profile["weighted_high_income_rate"].min(),
    })

segment_model_summary = pd.DataFrame(segment_model_rows)
segment_model_summary.round(4)

,k,inertia,smallest_weighted_segment_share,largest_weighted_segment_share,high_income_rate_range
0,3,4.257910e+09,0.2957,0.3539,0.1093
1,4,4.000674e+09,0.1599,0.3407,0.1113
2,5,3.856122e+09,0.0412,0.3214,0.1147
3,6,3.893394e+09,0.0686,0.3308,0.1286

In [33]:
profile_cols = [
    "segment",
    "weighted_share",
    "weighted_high_income_rate",
    "avg_age",
    "avg_weeks_worked",
    "top_education",
    "top_class_of_worker",
    "top_marital_stat",
    "top_major_occupation",
]

for k in candidate_ks:
    print(f"Segment profile for k={k}")
    display(segment_profiles[k][profile_cols].round(3))

Segment profile for k=3

,segment,weighted_share,weighted_high_income_rate,avg_age,avg_weeks_worked,top_education,top_class_of_worker,top_marital_stat,top_major_occupation
2,2,0.354,0.111,38.409,44.263,"High school graduate, Some college but no degree, Bachelors degree(BA AB BS)","Private, Self-employed-not incorporated, Local government","Married-civilian spouse present, Never married, Divorced","Adm support including clerical, Professional specialty, Executive admin and managerial"
0,0,0.350,0.125,38.601,45.332,"High school graduate, Some college but no degree, Bachelors degree(BA AB BS)","Private, Self-employed-not incorporated, Local government","Married-civilian spouse present, Never married, Divorced","Adm support including clerical, Professional specialty, Executive admin and managerial"
1,1,0.296,0.016,57.576,1.027,"High school graduate, Some college but no degree, 7th and 8th grade","Not in universe, Never worked, Self-employed-not incorporated","Married-civilian spouse present, Widowed, Never married","Not in universe, Farming forestry and fishing, Other service"

Segment profile for k=4

,segment,weighted_share,weighted_high_income_rate,avg_age,avg_weeks_worked,top_education,top_class_of_worker,top_marital_stat,top_major_occupation
3,3,0.341,0.128,38.694,46.100,"High school graduate, Some college but no degree, Bachelors degree(BA AB BS)","Private, Self-employed-not incorporated, Local government","Married-civilian spouse present, Never married, Divorced","Adm support including clerical, Professional specialty, Executive admin and managerial"
2,2,0.337,0.114,38.316,45.782,"High school graduate, Some college but no degree, Bachelors degree(BA AB BS)","Private, Self-employed-not incorporated, Local government","Married-civilian spouse present, Never married, Divorced","Adm support including clerical, Professional specialty, Executive admin and managerial"
1,1,0.162,0.017,55.960,2.436,"High school graduate, Some college but no degree, 7th and 8th grade","Not in universe, Private, Self-employed-not incorporated","Married-civilian spouse present, Widowed, Never married","Not in universe, Other service, Adm support including clerical"
0,0,0.160,0.017,56.056,1.972,"High school graduate, Some college but no degree, 7th and 8th grade","Not in universe, Private, Self-employed-not incorporated","Married-civilian spouse present, Widowed, Never married","Not in universe, Other service, Adm support including clerical"

Segment profile for k=5

,segment,weighted_share,weighted_high_income_rate,avg_age,avg_weeks_worked,top_education,top_class_of_worker,top_marital_stat,top_major_occupation
4,4,0.321,0.116,38.241,45.560,"High school graduate, Some college but no degree, Bachelors degree(BA AB BS)","Private, Self-employed-not incorporated, Local government","Married-civilian spouse present, Never married, Divorced","Adm support including clerical, Professional specialty, Executive admin and managerial"
3,3,0.317,0.131,38.627,45.782,"High school graduate, Some college but no degree, Bachelors degree(BA AB BS)","Private, Self-employed-not incorporated, Local government","Married-civilian spouse present, Never married, Divorced","Professional specialty, Adm support including clerical, Executive admin and managerial"
1,1,0.161,0.017,56.112,2.397,"High school graduate, Some college but no degree, 7th and 8th grade","Not in universe, Private, Self-employed-not incorporated","Married-civilian spouse present, Widowed, Never married","Not in universe, Other service, Farming forestry and fishing"
2,2,0.159,0.017,56.144,1.934,"High school graduate, Some college but no degree, 7th and 8th grade","Not in universe, Private, Self-employed-not incorporated","Married-civilian spouse present, Widowed, Never married","Not in universe, Other service, Adm support including clerical"
0,0,0.041,0.083,39.447,48.604,"High school graduate, Some college but no degree, Bachelors degree(BA AB BS)","Private, Local government, Federal government","Married-civilian spouse present, Never married, Divorced","Adm support including clerical, Precision production craft & repair, Professional specialty"

Segment profile for k=6

,segment,weighted_share,weighted_high_income_rate,avg_age,avg_weeks_worked,top_education,top_class_of_worker,top_marital_stat,top_major_occupation
3,3,0.331,0.132,39.071,47.256,"High school graduate, Some college but no degree, Bachelors degree(BA AB BS)","Private, Self-employed-not incorporated, Local government","Married-civilian spouse present, Never married, Divorced","Adm support including clerical, Professional specialty, Executive admin and managerial"
2,2,0.286,0.130,39.798,48.701,"High school graduate, Some college but no degree, Bachelors degree(BA AB BS)","Private, Local government, Self-employed-not incorporated","Married-civilian spouse present, Never married, Divorced","Adm support including clerical, Professional specialty, Executive admin and managerial"
0,0,0.127,0.019,62.793,1.280,"High school graduate, Some college but no degree, 7th and 8th grade","Not in universe, Self-employed-not incorporated, Private","Married-civilian spouse present, Widowed, Divorced","Not in universe, Farming forestry and fishing, Adm support including clerical"
5,5,0.104,0.025,69.544,1.309,"High school graduate, 7th and 8th grade, Some college but no degree","Not in universe, Private, Self-employed-not incorporated","Married-civilian spouse present, Widowed, Divorced","Not in universe, Farming forestry and fishing, Executive admin and managerial"
4,4,0.084,0.019,29.968,19.595,"High school graduate, Some college but no degree, Bachelors degree(BA AB BS)","Private, Not in universe, Self-employed-not incorporated","Never married, Married-civilian spouse present, Divorced","Not in universe, Other service, Precision production craft & repair"
1,1,0.069,0.003,31.111,4.896,"High school graduate, Some college but no degree, Bachelors degree(BA AB BS)","Not in universe, Private, Self-employed-not incorporated","Married-civilian spouse present, Never married, Divorced","Not in universe, Other service, Adm support including clerical"

In [34]:
selected_segment_k = 6
selected_segment_profile = segment_profiles[selected_segment_k]

print(f"Selected segmentation candidate: k={selected_segment_k}")
selected_segment_profile[profile_cols].round(3)

Selected segmentation candidate: k=6

,segment,weighted_share,weighted_high_income_rate,avg_age,avg_weeks_worked,top_education,top_class_of_worker,top_marital_stat,top_major_occupation
3,3,0.331,0.132,39.071,47.256,"High school graduate, Some college but no degree, Bachelors degree(BA AB BS)","Private, Self-employed-not incorporated, Local government","Married-civilian spouse present, Never married, Divorced","Adm support including clerical, Professional specialty, Executive admin and managerial"
2,2,0.286,0.130,39.798,48.701,"High school graduate, Some college but no degree, Bachelors degree(BA AB BS)","Private, Local government, Self-employed-not incorporated","Married-civilian spouse present, Never married, Divorced","Adm support including clerical, Professional specialty, Executive admin and managerial"
0,0,0.127,0.019,62.793,1.280,"High school graduate, Some college but no degree, 7th and 8th grade","Not in universe, Self-employed-not incorporated, Private","Married-civilian spouse present, Widowed, Divorced","Not in universe, Farming forestry and fishing, Adm support including clerical"
5,5,0.104,0.025,69.544,1.309,"High school graduate, 7th and 8th grade, Some college but no degree","Not in universe, Private, Self-employed-not incorporated","Married-civilian spouse present, Widowed, Divorced","Not in universe, Farming forestry and fishing, Executive admin and managerial"
4,4,0.084,0.019,29.968,19.595,"High school graduate, Some college but no degree, Bachelors degree(BA AB BS)","Private, Not in universe, Self-employed-not incorporated","Never married, Married-civilian spouse present, Divorced","Not in universe, Other service, Precision production craft & repair"
1,1,0.069,0.003,31.111,4.896,"High school graduate, Some college but no degree, Bachelors degree(BA AB BS)","Not in universe, Private, Self-employed-not incorporated","Married-civilian spouse present, Never married, Divorced","Not in universe, Other service, Adm support including clerical"

In [35]:
print("Model comparison, sorted by retail marketing selection rule: F1 first, ROC AUC second:")
display(model_comparison[["comparison_group", "model", "marketing_selection_metric", "roc_auc", "f1", "precision", "recall", "accuracy"]])

print(f"Selected classification model: {best_classifier_name}")
print(f"Selected threshold: {best_threshold:.2f}")
display(best_threshold_metrics.round(4))

print("Segmentation cluster-count comparison:")
display(segment_model_summary.round(4))

print(f"Selected segmentation candidate: k={selected_segment_k}")
display(selected_segment_profile[profile_cols].round(3))

Model comparison, sorted by retail marketing selection rule: F1 first, ROC AUC second:

,comparison_group,model,marketing_selection_metric,roc_auc,f1,precision,recall,accuracy
10,challenger,lightgbm_tuned,0.601014,0.954432,0.601014,0.754484,0.499425,0.957150
5,primary,lightgbm_unweighted,0.591254,0.954593,0.591254,0.763869,0.482272,0.956909
9,challenger,xgboost_tuned,0.572724,0.953930,0.572724,0.774013,0.454521,0.956174
4,primary,xgboost_unweighted,0.557527,0.952535,0.557527,0.773169,0.435940,0.955285
8,challenger,lightgbm_balanced,0.483817,0.954659,0.483817,0.331573,0.894560,0.876649
7,challenger,xgboost_balanced,0.462415,0.951924,0.462415,0.311533,0.896711,0.865266
1,primary,logistic_regression,0.445895,0.946054,0.445895,0.296553,0.898251,0.855733
3,primary,random_forest,0.417025,0.941357,0.417025,0.271405,0.899808,0.837427
6,challenger,extra_trees,0.386930,0.931968,0.386930,0.247340,0.888191,0.818116
2,primary,shallow_decision_tree,0.365065,0.912099,0.365065,0.228841,0.902013,0.797240
0,primary,dummy_baseline,0.000000,0.500000,0.000000,0.000000,0.000000,0.935378

Selected classification model: lightgbm_tuned
Selected threshold: 0.35

,threshold,accuracy,precision,recall,f1,roc_auc,weighted_predicted_positive_share
6,0.35,0.954,0.6536,0.6132,0.6327,0.9544,0.0606

Segmentation cluster-count comparison:

,k,inertia,smallest_weighted_segment_share,largest_weighted_segment_share,high_income_rate_range
0,3,4.257910e+09,0.2957,0.3539,0.1093
1,4,4.000674e+09,0.1599,0.3407,0.1113
2,5,3.856122e+09,0.0412,0.3214,0.1147
3,6,3.893394e+09,0.0686,0.3308,0.1286

Selected segmentation candidate: k=6

,segment,weighted_share,weighted_high_income_rate,avg_age,avg_weeks_worked,top_education,top_class_of_worker,top_marital_stat,top_major_occupation
3,3,0.331,0.132,39.071,47.256,"High school graduate, Some college but no degree, Bachelors degree(BA AB BS)","Private, Self-employed-not incorporated, Local government","Married-civilian spouse present, Never married, Divorced","Adm support including clerical, Professional specialty, Executive admin and managerial"
2,2,0.286,0.130,39.798,48.701,"High school graduate, Some college but no degree, Bachelors degree(BA AB BS)","Private, Local government, Self-employed-not incorporated","Married-civilian spouse present, Never married, Divorced","Adm support including clerical, Professional specialty, Executive admin and managerial"
0,0,0.127,0.019,62.793,1.280,"High school graduate, Some college but no degree, 7th and 8th grade","Not in universe, Self-employed-not incorporated, Private","Married-civilian spouse present, Widowed, Divorced","Not in universe, Farming forestry and fishing, Adm support including clerical"
5,5,0.104,0.025,69.544,1.309,"High school graduate, 7th and 8th grade, Some college but no degree","Not in universe, Private, Self-employed-not incorporated","Married-civilian spouse present, Widowed, Divorced","Not in universe, Farming forestry and fishing, Executive admin and managerial"
4,4,0.084,0.019,29.968,19.595,"High school graduate, Some college but no degree, Bachelors degree(BA AB BS)","Private, Not in universe, Self-employed-not incorporated","Never married, Married-civilian spouse present, Divorced","Not in universe, Other service, Precision production craft & repair"
1,1,0.069,0.003,31.111,4.896,"High school graduate, Some college but no degree, Bachelors degree(BA AB BS)","Not in universe, Private, Self-employed-not incorporated","Married-civilian spouse present, Never married, Divorced","Not in universe, Other service, Adm support including clerical"